---
deployment:
  tasks:
    - export DEPLOYPATH=/home/goodsmux/staging.goodnrowdy.com
    - /usr/bin/rsync -aq --delete --exclude='.git/' --exclude='node_modules/' --exclude='.next/cache/' . $DEPLOYPATH
    - find $DEPLOYPATH/.next -type d -exec chmod 755 {} \;
    - find $DEPLOYPATH/.next -type f -exec chmod 644 {} \;
    - chmod 755 $DEPLOYPATH
    - export HOME=/home/goodsmux
    - cd $DEPLOYPATH && /home/goodsmux/nodevenv/staging.goodnrowdy.com/20/bin/npm install --omit=dev
    - touch $DEPLOYPATH/tmp/restart.txt
