---
deployment:
  tasks:
    - export DEPLOYPATH=/home/goodsmux/staging.goodnrowdy.com
    - /usr/bin/rsync -aq --exclude='.git/' --exclude='node_modules/' . $DEPLOYPATH
    - find $DEPLOYPATH/.next -type d -exec chmod 755 {} +
    - export HOME=/home/goodsmux
    - cd $DEPLOYPATH && /home/goodsmux/nodevenv/staging.goodnrowdy.com/20/bin/npm install --omit=dev
